use std::{env, fs, net::IpAddr};

use super::shell::shell_join;

pub(super) struct ContainerDnsConfig {
    pub(super) nameservers: Vec<String>,
    pub(super) include_default_gateway: bool,
}

impl ContainerDnsConfig {
    pub(super) fn display_nameservers(&self) -> String {
        let mut nameservers = Vec::new();
        if self.include_default_gateway {
            nameservers.push("guest default gateway".to_string());
        }
        nameservers.extend(self.nameservers.iter().cloned());
        nameservers.join(", ")
    }
}

pub(super) fn container_dns_config() -> ContainerDnsConfig {
    let configured = env::var("STATIX_CONTAINER_DNS")
        .ok()
        .map(|value| parse_configured_nameservers(&value))
        .unwrap_or_default();
    if !configured.is_empty() {
        return ContainerDnsConfig {
            nameservers: configured,
            include_default_gateway: false,
        };
    }

    let mut nameservers = Vec::new();
    for path in ["/run/systemd/resolve/resolv.conf", "/etc/resolv.conf"] {
        let Ok(contents) = fs::read_to_string(path) else {
            continue;
        };
        nameservers.extend(parse_resolv_conf_nameservers(&contents));
        if !nameservers.is_empty() {
            return ContainerDnsConfig {
                nameservers: dedupe_nameservers(nameservers),
                include_default_gateway: true,
            };
        }
    }

    ContainerDnsConfig {
        nameservers: Vec::new(),
        include_default_gateway: true,
    }
}

pub(super) fn parse_configured_nameservers(value: &str) -> Vec<String> {
    dedupe_nameservers(
        value
            .split(',')
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToOwned::to_owned)
            .collect(),
    )
}

pub(super) fn parse_resolv_conf_nameservers(contents: &str) -> Vec<String> {
    dedupe_nameservers(
        contents
            .lines()
            .filter_map(|line| line.split('#').next())
            .map(str::trim)
            .filter_map(|line| line.strip_prefix("nameserver"))
            .filter_map(|value| value.split_whitespace().next())
            .filter(|value| !is_loopback_or_unspecified_address(value))
            .map(ToOwned::to_owned)
            .collect(),
    )
}

fn is_loopback_or_unspecified_address(value: &str) -> bool {
    value
        .parse::<IpAddr>()
        .map(|address| address.is_loopback() || address.is_unspecified())
        .unwrap_or(false)
}

fn dedupe_nameservers(nameservers: Vec<String>) -> Vec<String> {
    let mut deduped = Vec::new();
    for nameserver in nameservers {
        if !deduped.contains(&nameserver) {
            deduped.push(nameserver);
        }
    }
    deduped
}

pub(super) fn guest_resolv_conf_command(config: &ContainerDnsConfig) -> String {
    let mut lines = vec!["# Generated by statix-agent for job container DNS".to_string()];
    lines.extend(
        config
            .nameservers
            .iter()
            .map(|nameserver| format!("nameserver {nameserver}")),
    );
    lines.push("options timeout:2 attempts:2".to_string());

    let write_resolv_conf = format!("printf '%s\\n' {} > /etc/resolv.conf", shell_join(&lines));
    if !config.include_default_gateway {
        return format!("rm -f /etc/resolv.conf && {write_resolv_conf}");
    }

    format!(
        "gateway=$(ip -4 route show default 2>/dev/null | awk '{{print $3; exit}}'); rm -f /etc/resolv.conf && {{ printf '%s\\n' '# Generated by statix-agent for job container DNS'; if [ -n \"$gateway\" ]; then printf '%s\\n' \"nameserver $gateway\"; fi; printf '%s\\n' {}; }} > /etc/resolv.conf",
        shell_join(&lines[1..])
    )
}
